---
title: "클러스터링 : 고객별"
author: "June"
date: '2020 4 14 '
output: html_document
---


(@) ***변수 추출 및 데이터타입 변환***

+  고객별 클러스터링을 위한 데이터 전처리

```{r code1, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

M_ALL <- read.csv(file = 'C:/app/R/New_R_workspace/롯데/M_ALL.csv')

colnames(M_ALL)

# "CLNT_ID","HITS_SEQ","PD_BUY_AM","PD_BUY_CT","PD_BUY_TOT","TOT_PAG_VIEW_CT","TOT_SESS_HR_V" 추출
CS_CLUST <- M_ALL[, c(1,3,7,8,9,19,20)]
colnames(CS_CLUST)

# NA값 확인 및 제거
library(dplyr)
summary(CS_CLUST)
CS_CLUST <- CS_CLUST %>% filter(! is.na(TOT_PAG_VIEW_CT))
summary(CS_CLUST)

# 고객코드(CLNT_ID)별 그룹화

CS_CLUST <-
  CS_CLUST %>% group_by(CLNT_ID) %>% summarise(mean_HITS_SEQ = mean(HITS_SEQ),
                                               mean_PD_BUY_AM = mean(PD_BUY_AM),
                                               mean_PD_BUY_CT= mean(PD_BUY_CT),
                                               mean_PD_BUY_TOT= mean(PD_BUY_TOT),
                                               mean_TOT_PAG_VIEW_CT= mean(TOT_PAG_VIEW_CT),
                                               mean_TOT_SESS_HR_V= mean(TOT_SESS_HR_V))
CS_CLUST <- as.data.frame(CS_CLUST)

# View(CS_CLUST)

```

+ 변수의 척도화 수행(표준화)

```{r code2, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

# CLNT_ID 변수 제거
CS_CLUST <- CS_CLUST[-1]
colnames(CS_CLUST)

# 척도화
library(pls)
Z_CS_CLUST <- stdize( as.matrix(CS_CLUST) )


```


(@) ***클러스터링***


+ 클러스터링 수행 (k-means with k = 5)

```{r code3, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

kmc <- kmeans(Z_CS_CLUST, centers = 5)

```

+ 클러스터링 결과 시각화

```{r code4, echo=TRUE, message=FALSE, warning=FALSE}

plot(Z_CS_CLUST, col = kmc$cluster, pch = 16)

```


+ 클러스터링 결과 변수에 담기, subset 생성

```{r code5, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

# 새변수 cluster 에 군집화 결과 담기 
CS_CLUST <- CS_CLUST %>% mutate(cluster = kmc$cluster)

# 각 군집별 subset 생성
sub_1 <- CS_CLUST %>% filter(cluster == 1)
sub_2 <- CS_CLUST %>% filter(cluster == 2)
sub_3 <- CS_CLUST %>% filter(cluster == 3)
sub_4 <- CS_CLUST %>% filter(cluster == 4)
sub_5 <- CS_CLUST %>% filter(cluster == 5)

# --------------------------------------------------------------------------
# 고객 분류를 통해 금액, 대분류와 관련한 고객의 특성을 찾고자 하였으나, 
# 클러스터링 결과로는 유의미해보이는 클러스터링 집단이 나뉘었으나,
# 대분류와 관련한 뚜렷한 고객의 특성을 찾기 어려워 
# 개별적인 고객분류를 사용하기로 한다.
# --------------------------------------------------------------------------

```






