---
title: "요소별 하락요인"
author: "June"
date: '2020 4 08 '
output: html_document
---


(@) ***고객군별***


+ 양적 변수 기초통계량

```{r code1, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
M_ALL <- read.csv(file = 'C:/app/R/New_R_workspace/롯데/M_ALL.csv')

#   1) Pastec 패키지
library(pastecs)


test_fin <- na.omit(M_ALL)
# colnames(test_fin)

b1_stat <- stat.desc(test_fin)[,c(3,7,8,9,12,17,19,20)]

round(b1_stat, 2)

```



```{r code2, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

#   2) summary 함수
b2_stat <- summary(test_fin[,c(3,7,8,9,12,17,19,20)])

b2_stat

```



(@) ***개별변수 특성***


+ HITS_SEQ : Numeric

```{r code3, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

# (1) 확률밀도 함수

# qplot(M_ALL$HITS_SEQ)
# hist(test_fin$HITS_SEQ)
hist(test_fin$HITS_SEQ, freq = F, breaks = 100)
lines(density(test_fin$HITS_SEQ), col = 'red', lwd = 2)

# (2) 왜도 & 첨도
library(e1071)
skewness(test_fin$HITS_SEQ) # 1.93188
kurtosis(test_fin$HITS_SEQ) # 6.874405

```


+ PD_BUY_AM : Numeric

```{r code4, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

# (1) 확률밀도 함수

# hist(test_fin$PD_BUY_AM)
hist(test_fin$PD_BUY_AM, freq = F, breaks = 1000000)
lines(density(test_fin$PD_BUY_AM), col = 'red', lwd = 2)

# (2) 왜도 & 첨도
skewness(test_fin$PD_BUY_AM) # 15.07033
kurtosis(test_fin$PD_BUY_AM) # 559.9662

# (3) 정규성:
# shapiro.test(test_fin$PD_BUY_AM) # 실행 不可

```


+ PD_BUY_CT : Numeric

```{r code5, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

# (1) 확률밀도 함수

# qplot(M_ALL$PD_BUY_CT)
# hist(test_fin$PD_BUY_CT)
hist(test_fin$PD_BUY_CT, freq = F, breaks = 10)
lines(density(test_fin$PD_BUY_CT), col = 'red', lwd = 2)

# (2) 왜도 & 첨도
skewness(test_fin$PD_BUY_CT) # 186.1892
kurtosis(test_fin$PD_BUY_CT) # 59083.43

```


+ PD_BUY_TOT : Numeric

```{r code6, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

# (1) 확률밀도 함수

# qplot(M_ALL$PD_BUY_TOT)
# hist(test_fin$PD_BUY_TOT)
hist(test_fin$PD_BUY_TOT, freq = F, breaks = 1000)
lines(density(test_fin$PD_BUY_TOT), col = 'red', lwd = 2)

# (2) 왜도 & 첨도
skewness(test_fin$PD_BUY_TOT) # 15.79321
kurtosis(test_fin$PD_BUY_TOT) # 637.4551

# (3) 정규성:
# shapiro.test(test_fin$PD_BUY_TOT) # 실행 不可

```


+ CLNT_AGE : Numeric

```{r code7, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

# (1) 확률밀도 함수

# qplot(M_ALL$CLNT_AGE)
# hist(test_fin$CLNT_AGE)
hist(test_fin$CLNT_AGE, freq = F, breaks = 100)
lines(density(test_fin$CLNT_AGE), col = 'red', lwd = 2)

# (2) 왜도 & 첨도
skewness(test_fin$CLNT_AGE) # 0.2857157
kurtosis(test_fin$CLNT_AGE) # 3.740531

# (3) 정규성:
# shapiro.test(test_fin$CLNT_AGE) # 실행 不可

```


+ SESS_SEQ : Numeric

```{r code8, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

# (1) 확률밀도 함수

# qplot(M_ALL$SESS_SEQ)
# hist(test_fin$SESS_SEQ)
hist(test_fin$SESS_SEQ, freq = F, breaks = 100)
lines(density(test_fin$SESS_SEQ), col = 'red', lwd = 2)

# (2) 왜도 & 첨도
skewness(test_fin$SESS_SEQ) # 3.134827
kurtosis(test_fin$SESS_SEQ) # 17.92146

# (3) 정규성:
# shapiro.test(test_fin$SESS_SEQ) # 실행 不可

```


+ TOT_PAG_VIEW_CT : Numeric

```{r code9, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

# (1) 확률밀도 함수

# qplot(M_ALL$TOT_PAG_VIEW_CT)
# hist(test_fin$TOT_PAG_VIEW_CT)
hist(test_fin$TOT_PAG_VIEW_CT, freq = F, breaks = 100)
lines(density(test_fin$TOT_PAG_VIEW_CT), col = 'red', lwd = 2)

# (2) 왜도 & 첨도
skewness(test_fin$TOT_PAG_VIEW_CT) # 1.690908
kurtosis(test_fin$TOT_PAG_VIEW_CT) # 5.633332

# (3) 정규성:
# shapiro.test(test_fin$TOT_PAG_VIEW_CT) # 실행 不可

```


+ TOT_SESS_HR_V : Numeric

```{r code10, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

# (1) 확률밀도 함수

# qplot(M_ALL$TOT_SESS_HR_V)
# hist(test_fin$TOT_SESS_HR_V)
hist(test_fin$TOT_SESS_HR_V, freq = F, breaks = 100)
lines(density(test_fin$TOT_SESS_HR_V), col = 'red', lwd = 2)

# (2) 왜도 & 첨도
skewness(test_fin$TOT_SESS_HR_V) # 3.195901
kurtosis(test_fin$TOT_SESS_HR_V) # 32.5718

# (3) 정규성:
# shapiro.test(test_fin$TOT_SESS_HR_V) # 실행 不可

```



(@) ***상관행렬***

+ 상관 행렬 

```{r code11, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

M_ALL_3 <- M_ALL[,c(3,7,8,9,12,17,19,20)]
M_ALL_3 <- na.omit(M_ALL_3)


cor_05 <-cor(M_ALL_3)
cor_05

```


+ 상관 행렬 (correlogram)



(@) ***상관 계수***


+ TOT_PAG_VIEW_CT & TOT_SESS_HR_V


```{r code12, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
library(dplyr)
library(ggpubr)

g1 <- M_ALL_3 %>%
    sample_frac(0.0005) %>%
    ggscatter(x = "TOT_PAG_VIEW_CT",
              y = "TOT_SESS_HR_V",
              add = "reg.line",
              color = "#00FFFF",size = 2, shape = 19, alpha = 0.5,
              conf.int = TRUE,
              cor.coef = TRUE,
              cor.coeff.args = list(method = "pearson",
                                    label.x = 3, label.sep = "\n"),
              xlab = "TOT_PAG_VIEW_CT",
              ylab = "TOT_SESS_HR_V",
              add.params = list(color = "red",
                                fill = "black"))

g1

```


+ HITS_SEQ & TOT_SESS_HR_V


```{r code13, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

g2 <- M_ALL_3 %>%
  sample_frac(0.0005) %>%
  ggscatter(x = "HITS_SEQ",
            y = "TOT_SESS_HR_V",
            add = "reg.line",
            color = "#00FFFF",size = 2, shape = 19, alpha = 0.5,
            conf.int = TRUE,
            cor.coef = TRUE,
            cor.coeff.args = list(method = "pearson",
                                  label.x = 3, label.sep = "\n"),
            xlab = "HITS_SEQ",
            ylab = "TOT_SESS_HR_V",
            add.params = list(color = "red",
                              fill = "black"))
g2

```


+ HITS_SEQ & TOT_PAG_VIEW_CT

```{r code14, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

g3 <- M_ALL_3 %>%
  sample_frac(0.0005) %>%
  ggscatter(x = "HITS_SEQ",
            y = "TOT_PAG_VIEW_CT",
            add = "reg.line",
            color = "#00FFFF",size = 2, shape = 19, alpha = 0.5,
            conf.int = TRUE,
            cor.coef = TRUE,
            cor.coeff.args = list(method = "pearson",
                                  label.x = 3, label.sep = "\n"),
            xlab = "HITS_SEQ",
            ylab = "TOT_PAG_VIEW_CT",
            add.params = list(color = "red",
                              fill = "black"))

g3

```





















