---
title: "요소별 하락원인"
author: "June"
date: '2020 4 08 '
output: html_document
---


(@) ***월별 고객 구분***


+ 데이터 정제

```{r code1, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

M_ALL <- read.csv(file = 'C:/app/R/New_R_workspace/롯데/M_ALL.csv')

df <- M_ALL[,c(1,2,3,4,7,8,9,13,18)]

library(dplyr)

# 월별 구분
month_4 <- df %>% filter(substr(SESS_DT, 1, 7) == '2018-04')
month_5 <- df %>% filter(substr(SESS_DT, 1, 7) == '2018-05')
month_6 <- df %>% filter(substr(SESS_DT, 1, 7) == '2018-06')
month_7 <- df %>% filter(substr(SESS_DT, 1, 7) == '2018-07')
month_8 <- df %>% filter(substr(SESS_DT, 1, 7) == '2018-08')
month_9 <- df %>% filter(substr(SESS_DT, 1, 7) == '2018-09')


# CLNT_ID 별로 PD_BUY_TOT
month_4 <- month_4 %>% group_by(CLNT_ID) %>% 
  summarise(PD_BUY_TOT_sum = sum(PD_BUY_TOT))
month_5 <- month_5 %>% group_by(CLNT_ID) %>% 
  summarise(PD_BUY_TOT_sum = sum(PD_BUY_TOT))
month_6 <- month_6 %>% group_by(CLNT_ID) %>% 
  summarise(PD_BUY_TOT_sum = sum(PD_BUY_TOT))
month_7 <- month_7 %>% group_by(CLNT_ID) %>% 
  summarise(PD_BUY_TOT_sum = sum(PD_BUY_TOT))
month_8 <- month_8 %>% group_by(CLNT_ID) %>% 
  summarise(PD_BUY_TOT_sum = sum(PD_BUY_TOT))
month_9 <- month_9 %>% group_by(CLNT_ID) %>% 
  summarise(PD_BUY_TOT_sum = sum(PD_BUY_TOT))


# 데이터 프레임 변환

month_4 <- as.data.frame(month_4)
month_5 <- as.data.frame(month_5)
month_6 <- as.data.frame(month_6)
month_7 <- as.data.frame(month_7)
month_8 <- as.data.frame(month_8)
month_9 <- as.data.frame(month_9)



```


+ 월별 고객 등급 할당


```{r code2, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

# 4 월 

m4_tot <- month_4 %>%
mutate(Grade =
ifelse(PD_BUY_TOT_sum > 1666667, "VVIP",
ifelse(PD_BUY_TOT_sum > 416667 & PD_BUY_TOT_sum <= 1666667, 
       "VIP","Cust")))
# summary(m4_tot)
# View(m4_tot)
table(m4_tot$Grade)


# 5 월

m5_tot <- month_5 %>%
mutate(Grade =
ifelse(PD_BUY_TOT_sum > 1666667, "VVIP",
ifelse(PD_BUY_TOT_sum > 416667 & PD_BUY_TOT_sum <= 1666667, 
"VIP","Cust")))
# summary(m4_tot)
table(m5_tot$Grade)


# 6 월 

m6_tot <- month_6 %>%
mutate(Grade =
ifelse(PD_BUY_TOT_sum > 1666667, "VVIP",
ifelse(PD_BUY_TOT_sum > 416667 & PD_BUY_TOT_sum <= 1666667, 
"VIP","Cust")))
# summary(m4_tot)
table(m6_tot$Grade)


# 7 월 

m7_tot <- month_7 %>%
mutate(Grade =
ifelse(PD_BUY_TOT_sum > 1666667, "VVIP",
ifelse(PD_BUY_TOT_sum > 416667 & PD_BUY_TOT_sum <= 1666667, 
"VIP","Cust")))
# summary(m7_tot)
table(m7_tot$Grade)


# 8월 

m8_tot <- month_8 %>%
mutate(Grade =
ifelse(PD_BUY_TOT_sum > 1666667, "VVIP",
ifelse(PD_BUY_TOT_sum > 416667 & PD_BUY_TOT_sum <= 1666667, 
"VIP","Cust")))
# summary(m8_tot)
table(m8_tot$Grade)


# 9 월 

m9_tot <- month_9 %>%
mutate(Grade =
ifelse(PD_BUY_TOT_sum > 1666667, "VVIP",
ifelse(PD_BUY_TOT_sum > 416667 & PD_BUY_TOT_sum <= 1666667, 
"VIP","Cust")))
# summary(m8_tot)
table(m9_tot$Grade)

```



(@) ***월별 고객 교차분석***


+ Left-Outer Join : 4월 CLNT_ID 기준

```{r code3, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

# 4 & 5
m1_01 <- sqldf::sqldf("SELECT * FROM m4_tot
                       LEFT OUTER JOIN m5_tot
                       ON m4_tot.CLNT_ID =
                       m5_tot.CLNT_ID")

m1_01_t <- m1_01[,c(1,3,6)]


# 4 & 5 & 6
m1_01_t <- sqldf::sqldf("SELECT * FROM m1_01_t
                        LEFT OUTER JOIN m6_tot
                        ON m1_01_t.CLNT_ID =
                        m6_tot.CLNT_ID")

m1_01_t <- m1_01_t[,c(1,2,3,6)]


# 4 & 5 & 6 & 7
m1_01_t <- sqldf::sqldf("SELECT * FROM m1_01_t
                         LEFT OUTER JOIN m7_tot
                         ON m1_01_t.CLNT_ID =
                         m7_tot.CLNT_ID")

m1_01_t <- m1_01_t[,c(1,2,3,4,7)]


# 4 & 5 & 6 & 7 & 8
m1_01_t <- sqldf::sqldf("SELECT * FROM m1_01_t
                         LEFT OUTER JOIN m8_tot
                         ON m1_01_t.CLNT_ID =
                         m8_tot.CLNT_ID")

# colnames(m1_01_t)
m1_01_t <- m1_01_t[,c(1,2,3,4,5,8)]


# 4 & 5 & 6 & 7 & 8 & 9
m1_01_t <- sqldf::sqldf("SELECT * FROM m1_01_t
                         LEFT OUTER JOIN m9_tot
                         ON m1_01_t.CLNT_ID =
                         m9_tot.CLNT_ID")


# colnames(m1_01_t)
m1_01_t <- m1_01_t[,c(1,2,3,4,5,6,9)]

# 총합

# summary(m1_01_t)
colnames(m1_01_t) <- c("CLNT_ID", "Grade_4","Grade_5","Grade_6",
                       "Grade_7","Grade_8","Grade_9")

```


+ 이탈율

```{r code4, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

exit <- m1_01_t %>% 
      filter(!is.na(Grade_4) & !is.na(Grade_5) & !is.na(Grade_6) &
               !is.na(Grade_7) & !is.na(Grade_8) & !is.na(Grade_9)) 

```



(@) ***교차분석 테이블***

+ M + 1 Transition

```{r code5, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
library(gmodels)

# (1) 4 ~ 5 transition
CrossTable(m1_01_t$Grade_4, m1_01_t$Grade_5, chisq = F)

# (2) 5 ~ 6 transition
CrossTable(m1_01_t$Grade_5, m1_01_t$Grade_6, chisq = F)

# (3) 6 ~ 7 transition
CrossTable(m1_01_t$Grade_6, m1_01_t$Grade_7, chisq = F)

# (4) 7 ~ 8 transition
CrossTable(m1_01_t$Grade_7, m1_01_t$Grade_8, chisq = F)

# (4) 8 ~ 9 transition
CrossTable(m1_01_t$Grade_8, m1_01_t$Grade_9, chisq = F)

```


+ M + 2 Transition

```{r code6, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

# (1) 4 ~ 6 transition
CrossTable(m1_01_t$Grade_4, m1_01_t$Grade_6, chisq = F)

# (2) 5 ~ 7 transition
CrossTable(m1_01_t$Grade_5, m1_01_t$Grade_7, chisq = F)

# (3) 6 ~ 8 transition
CrossTable(m1_01_t$Grade_6, m1_01_t$Grade_8, chisq = F)

# (4) 7 ~ 9 transition
CrossTable(m1_01_t$Grade_7, m1_01_t$Grade_9, chisq = F)

```


+ M + 3 Transition

```{r code7, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}

# (1) 4 ~ 7 transition
CrossTable(m1_01_t$Grade_4, m1_01_t$Grade_7, chisq = F)

# (2) 5 ~ 8 transition
CrossTable(m1_01_t$Grade_5, m1_01_t$Grade_8, chisq = F)

# (3) 6 ~ 9 transition
CrossTable(m1_01_t$Grade_6, m1_01_t$Grade_9, chisq = F)


#   ⅳ. M + 6
CrossTable(m1_01_t$Grade_4, m1_01_t$Grade_9, chisq = F)

```






















